// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"UResNode/internal/svc"
	resServer "UResNode/internal/handler/resServer"
	test "UResNode/internal/handler/test"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
		{
			Method:  http.MethodPost,
			Path:    "/upload/res",
			Handler: resServer.UploadResHandler(serverCtx),
		},
		{
			Method:  http.MethodOptions,
			Path:    "/health",
			Handler: resServer.HealthHandler(serverCtx),
		},
}, 
	)

	engine.AddRoutes(
		[]rest.Route{
		{
			Method:  http.MethodPost,
			Path:    "/test/refresh",
			Handler: test.TestRefreshTokenHandler(serverCtx),
		},
}, 
	)
}
